[build]
  # Build command
  command = "npm run build"
  
  # Directory to deploy (Next.js static export)
  publish = "out"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
